### PR TITLE
[APIv3] Add default value for license

### LINKED ISSUE #905: CC-BY API setting
**Is your feature request related to a problem? Please describe.**
Currently, the Integreat content is CC BY-NC 4.0 licensed. The Open Data definition requires that there is no limitation to the use of data. We should have a setting that allows licensing content with CC BY 4.0 without the Non-Commercial clause.

**Describe the solution you'd like**
Add an license property to the sites endpoint. The default value is "CC BY-NC 4.0". When enabling the "Open Data" setting, this should switch to "CC BY 4.0".

### PR DESCRIPTION
**Pull request by svenseeberg**
* The license-name and license-url need a 'CC BY-NC 4.0'
  and link to the license description if the value is
  an empty string.
* Fixes #905

### CODE REVIEW

**Comment by svenseeberg** [comment]
@timoludwig I guess this could be fully done within the SQL query itself. What do you think?

**Comment by svenseeberg** [comment]
Oh, and the default values could come from yet another setting.

**Comment by timoludwig** [comment]
As #905 is on hold right now, should we close this PR?

**Comment by svenseeberg** [comment]
I guess so.

**Pull request closed without merging**
