### PR TITLE
Align master and develop

### PR DESCRIPTION
**Pull request by sven15**
With new pull requests, Github wants to merge all commits since Jul 7th. All but one of those commits are already merged. Hopefully this merge will bring back order into chaos.

See https://github.com/Integreat/cms/pull/416

### CODE REVIEW

**Comment by sven15** [comment]
No it doesnt. Ideas?

**Comment by mschrimpf** [comment]
This is only for PRs develop->master right?
I guess we could do a rebase + force-push... Are you sure that merging this PR would not fix it?

**Comment by sven15** [comment]
No, I'm not sure. We can try, but the amount of changed files is disturbing.
I have to think about the rebase option.

**Comment by sven15** [comment]
I tested the merge locally. It seems to solve the problem.

**Comment by mschrimpf** [comment]
OK I guess, we'll just try it. Note that there's probably no easy going back because this will affect a lot of the history.
Can you please fix the conflict, then we'll merge.

**Pull request merged**
