### PR TITLE
Update Plugins

### PR DESCRIPTION
**Pull request by svenseeberg**
## Aktualisierte Plugins

* Admin Dasboard RSS
* Adminimize
* Advanced Custom Fields
* Broken Link Checker
* CMS Tree View
* Disable New User Notificatons
* Two Factor
* User Role Editor
* WP Better E-Mails

## Tests
- [ ] Erste Schritte (@nassabay)
- [ ] Feedback (@nassabay)
- [ ] Veranstaltungen (@nassabay)
- [x] Revisionsprozess (@nassabay)
- [ ] Live Inhalte (@karthik-integreat)
- [x] Push Notifications (@karthik-integreat)
- [x] Benutzer & Rollen (@karthik-integreat)
- [x] Zentrale Angebote (@karthik-integreat)
- [x] Übersetzungsprozess (@karthik-integreat)

### CODE REVIEW

**Comment by svenseeberg** [comment]
Author chat needs to be rolled back.

**Comment by karthik-integreat** [comment]
Live-Inhalte: The site "Impfung gegen das Corona-Virus" does not exist in the drop down menu from the Deutschlandvorlage in other languages (Fa, Ru) while trying to embed it as a Live-Inhalt.
grafik

**Comment by karthik-integreat** [comment]
Push Notifications do not work in the Testumgebung. 
grafik

**Comment by svenseeberg** [comment]
@karthik-integreat push notifications are disabled on the test systems to prevent accidential messages to production cities. If you need to test push notifications, please copy the Network > Push Notifications Settings from the production system and remove them after testing.

**Comment by nassabay** [comment]
I cannot see any Information on the feedback section. Neither in the Testumgebung nor in a city. 
Screenshot (6)

**Comment by nassabay** [comment]
I cannot use filters in feedbacks. There are not really showing the results that I am waiting... for example when I choose: "Alle Kategorien" --> "Auswahl einschränken" I get nothing.
also, does it make more sense if "Alle Kategorien" appears first and then "Alle Kommentararten"?
Screenshot (6)

**Comment by nassabay** [comment]
I have activated the logo for the city of Augsburg. The logo is not visible in the PDF. No matter whether I call up the PDF through CMS or the website  
Logo nicht zu sehen

**Comment by nassabay** [comment]
I just tested "Push Notifications" in the test environment. I have used DE for all languages and the translation from DeepL for FR. In French there was a quotation mark (') and this came wrong in the message. I think it's the same problem we had in live environment with the special characters.  
Screenshot (12)

**Comment by nassabay** [comment]
I just created a event on german and do the translation into englisch lenguage. I can not see the event on the web site when I change the lenguage. 
Screenshot (25)

**Comment by nassabay** [comment]
When I create a event change the date to finish soon, so das I can test if the event automatisch disappears, I can see that the event is no more on cms but I still see it on the site 
Screenshot (28)

**Comment by nassabay** [comment]
I can't find the statistics option in the dashboard menu; but I can see that the option statistics for the last 12 months (chart) is into startseite menu. Shouldn't we have a statistics menu instead?
Screenshot (29)

**Comment by svenseeberg** [comment]
> I have activated the logo for the city of Augsburg. The logo is not visible in the PDF. No matter whether I call up the PDF through CMS or the website
> Logo nicht zu sehen

That is expected as we're only copying the database, not the images to the test sytem.

**Comment by svenseeberg** [comment]
> I can't find the statistics option in the dashboard menu; but I can see that the option statistics for the last 12 months (chart) is into startseite menu. Shouldn't we have a statistics menu instead?
> Screenshot (29)



> I can't find the statistics option in the dashboard menu; but I can see that the option statistics for the last 12 months (chart) is into startseite menu. Shouldn't we have a statistics menu instead?

The test system is disconnected from the Matomo server to prevent accidental tracking into live tracking databases.

**Pull request merged**
