### PR TITLE
Automatically activate themes

### PR DESCRIPTION
**Pull request by mschrimpf**
Please test if the activation works on
1. Windows
2. Linux

For further elaboration on why we really need to test this, see the commit comment.

### CODE REVIEW

**Comment by Meash** [comment]
@sven15 can you check linux please?
@sascha11110 can you check windows please?

**Comment by sven15** [comment]
It's working on linux. I think we can merge, as all our servers are running on linux right now.

**Comment by Meash** [comment]
According to Sven's analysis, the current implementation does not seem to work. We'll have to iterate over all `url`s and activate the themes per `url`. This requires us to find a way to perform cross-platform iteration.

**Comment by mschrimpf** [comment]
Closing this for now (no progress, not the most urgent thing).

**Pull request closed without merging**
