### PR TITLE
Prefix Integreat plugins with "ig-".

### LINKED ISSUE #327: Mark Plugins as 3rd-Party or being developed by us
It is currently hard to distinguish between plugins that are developed by us and plugins that were imported from a 3rd party. This is important so that we know which code we can change.

Maybe we can split the plugins folder in `3rd party` and `integreat` or prefix our plugins.

### PR DESCRIPTION
**Pull request by Meash**
resolves #327

### CODE REVIEW

**Comment by Meash** [comment]
@pblanz magst du mal drüber schauen?

**Comment by Meash** [comment]
@sven15 kannst du alternativ gucken?

**Comment by sven15** [comment]
Plugins are deactivated as expected. I can activate all of them but "Projektspezifische Benutzerrollen". It fails with "Dieses Plugin setzt eine Multisite Installation voraus".

**Comment by Meash** [comment]
So they are not deactivated right? Because they shouldn't be.
If all is fine, feel free to merge.

**Comment by sven15** [comment]
No, they will be deactivated but the can be reactivated at once.

**Comment by Meash** [comment]
Are they reactivated after calling the deploy script in your browser?

**Comment by sven15** [comment]
Ah right. Yes, the deploy.php is correctly activating the plugins. Just _Automatic Translation_ and _WordPress Importer_ are inactive.

**Comment by Meash** [comment]
Where does wordpress importer come from?
The automatic translation button works though, right?

**Comment by sven15** [comment]
I've got no idea about the importer. Checked out iss327-plugins_prefix, did a reset --hard and imported the current database dump.

The automatic translation button is active, but the automatic translation not. So I suppose it should be the other way around?

**Comment by Meash** [comment]
No that's how it should be. When automatic translation is active, a post is
translated on every save.
Just test if the translation button works please and then merge.

**Comment by sven15** [comment]
Automatic Translation Button is working. Merging.

**Pull request merged**
