### PR TITLE
Minor updates 4.4.4

### PR DESCRIPTION
**Pull request by sven15**
Updates wordpess to current 4.4.x release, including wpml plugins

### CODE REVIEW

**Comment by sven15** [comment]
Needs to be done.

**Comment by mschrimpf** [comment]
Let's give these updates a proper name in the future, I'd suggest `wordpress-update-4.4.4`.
Not a fan of `minor updates`.

**Comment by sven15** [comment]
as in patch level update?!.... 4.4.2 to 4.4.4

**Comment by mschrimpf** [comment]
Not sure what you mean by that. What I don't like about "minor updates" is that I'm not sure whether these are just Wordpress updates or also others. "wordpress-update" makes it more clear imo.

**Pull request merged**
