### PR TITLE
Master

### PR DESCRIPTION
**Pull request by sven15**
Bringing develop up to date with master - develop already has the same files, but commit history is diverging

### CODE REVIEW

**Comment by mschrimpf** [comment]
Can you give the pull request a more descriptive name please? I.e. write down the key points of this merge. Same for the description, write down what is being changed.

**Comment by sven15** [comment]
There are no differences between master and develop, just different commit histories. They should be merged back together.

**Comment by mschrimpf** [comment]
Sorry my bad - I thought this was a `develop -> master` merge.

**Comment by mschrimpf** [comment]
After thinking about this some more, I don't see a reason to merge master->develop. What's the issue with diverging commit histories? master simply has more merges.

**Comment by sven15** [comment]
okay, we can do that. okay with me

**Pull request closed without merging**
