### PR TITLE
New PDF export function, WPML update, recurring Events

### PR DESCRIPTION
**Pull request by svenseeberg**
* New WPML version with fixed flag sizes
* New PDF export
* Pimp API to support recurring events

### CODE REVIEW

**Comment by maxammann** [comment]
Looks good, but a small spec would be nice. Especially about the http request/response :)

**Comment by svenseeberg** [comment]
@sascha11110 can you please provide a short API definition for the app teams?

**Comment by Ponitac** [comment]
That will be a quite big update :D I guess I will run develop locally and do some testing

**Comment by svenseeberg** [comment]
@Ponitac yes, please.

**Comment by Ponitac** [comment]
The Problem with PDF in Arabic still exists or?

**Comment by svenseeberg** [comment]
Does it? Can you provide an example output for @sascha11110 ?

**Pull request merged**
