### PR TITLE
Master minor updates 4.4.4

### PR DESCRIPTION
**Pull request by sven15**
Updates wordpess to current 4.4.x release, including wpml plugins

### CODE REVIEW

**Comment by sven15** [comment]
No visible problems in develop / wordpress_test

**Comment by mschrimpf** [comment]
@sven15 We agreed to not merge pull requests directly into `master`... Please stop doing so unless it's something critical.
The process is: branch -> develop -> master.

**Comment by sven15** [comment]
The problem is, that our master branch is hopelessly behind develop. It's currently not possible to merge single updates into master. I think we need more development branches. Especially WordPress updates have to be implemented faster.,

**Comment by mschrimpf** [comment]
Want to open an issue to discuss? I think that might be a good idea, we should just have defined processes. The underlying problem is still that nobody really does testing imo.

**Pull request merged**
