### PR TITLE
Add permalinks to posts to API post attributes

### PR DESCRIPTION
**Pull request by svenseeberg**

### CODE REVIEW

**Comment by svenseeberg** [comment]
No idea why this is happening. Which URL did you call?

**Comment by Ponitac** [comment]
It occurs at every endpoint I try to call

**Comment by svenseeberg** [comment]
Is everything else working? add_filter() is a Wordpress core function.

**Comment by Ponitac** [comment]
The rest works fine, just the API shows me this error. Maybe Syntax Error?

**Comment by Ponitac** [comment]
Okay, I restarted the XAMPP VM and now everything works fine o.O

**Pull request merged**
