### PR TITLE
WP RTL, customized editor, WP 4.4.4, ContentLoader

### PR DESCRIPTION
**Pull request by sven15**
* WP RTL (#391) (#399)
* Customized editor plugin (#393)
* Wordpress 4.4.4 and WPML update (#394)
* Content Loader Base, Instance and Sprungbrett (#392)
* Fix for login bug (#401, #404)

### CODE REVIEW

**Comment by mschrimpf** [comment]
Please resolve the conflicts first

**Comment by sven15** [comment]
Currently tested:
* Content Loader Instance is working
* LTR and RTL buttons are available
* Plugins are updated (but again outdated ;-/)
* no issues with posts or showing posts encountered, WPML seems to be working.

**Comment by mschrimpf** [comment]
Wait there are only 4 changed files (related to ig-content-loader and customize editor.
Either files are missing or the message of this request is wrong.

**Comment by sven15** [comment]
I think it's correct, because WP 4.4.4 is already present in master ... in that sense: yes the Pull Request message is wrong.

**Comment by sven15** [comment]
Tested login on local system - pending on cms-test.integreat-app.de pending

**Pull request merged**
