### PR TITLE
Adjust Migration Script for Replacing web. to cms. inside wp_contents

### PR DESCRIPTION
**Pull request by Ponitac**

### CODE REVIEW

**Comment by svenseeberg** [comment]
I don't think that this is going to solve the problem of the wrong image paths. The parameters are changed for each run anyway. So it's probably a question of adding the correct SQL tables to the script.

**Comment by svenseeberg** [comment]
I don't see a need to to this in a pull request. The changes can be done locally. The first lines are comparable to a configuration file.

And by the way: the REPL_DOMAIN_* is supposed to contain the hostname while REPL_PATH_* is supposed to contain the path ;-)

**Comment by Ponitac** [comment]
I agree, but it thought it is necessary that you are seeing the changes I made :D if we run this script in the live environment I tried to make it less invasive. At the end there might be one typo and it corrupts all links in our database ;)

**Comment by svenseeberg** [comment]
I added the "required" changes to the API. Though, not tested yet. I'll do that hopefully today or tomorrow.

**Pull request closed without merging**
