### PR TITLE
remove http 403 status codes, helps with #234

### PR DESCRIPTION
**Pull request by sven15**
if we want to use mod_proxy we need to remove 403 status codes. mod_substitute will not touch 403 answers.

### CODE REVIEW

**Comment by Meash** [comment]
please add new plugins to the [plugin activation script](https://github.com/Integreat/cms/blob/develop/wp-activate-plugins.sh)

**Comment by sven15** [comment]
Added plugin to activation script

**Comment by Meash** [comment]
where exactly do the 403-forbidden codes come from again? can you explain why this is required?
It sounds strange that we have to change error-codes to "OK".

**Comment by sven15** [comment]
Example where Wordpress generates a 403 code: Login on https://cms.integreat-app.de/wp-login.php but your account is only valid for a specific site and not the whole network. After logging in, wordpress will present a list of sites / dashboards you can access and that the access to the network wide site has been denied. mod_substitute for some reason does not parse 403 pages. This results in links to vmkrcmar21.... to the dashboards after login on https://cms.integreat-app.de

As the error message is produced by wordpress, it can be considered a "soft" error message. Wordpress always (as far as I can see) always shows an additional information which states the problem. This message will not be influenced by the changed status code.

The plugin is hooked to the shutdown function and checks if the status code is 403. If that is the case, it will be changed to 200.

Apache status codes will not be affected.

**Comment by Meash** [comment]
Can we hook it to the special cases only or work around mod substitute?
Changing all 403 codes might be too much.

**Comment by sven15** [comment]
There is no alternative for mod_substitute. We could compile our own version of mod_substitute. But I can't see any reason why the status code is important.

**Comment by Meash** [comment]
Hmm we can keep it like it is for now.
It is still not clean to tamper with all status codes since there might be
other dependencies on them (e.g. by the browser) - let's hope it goes well.

**Pull request merged**
