### PR TITLE
recursive translation, site activation, webview, plugins refactoring, testing

### PR DESCRIPTION
**Pull request by mschrimpf**
Changes that should be tested manually
* webview: the contents are now displayed as a website as well (start from http://cms-test.integreat-app.de/wp-admin/)
* recursive translation: translate a page's parent if it is not yet translated
* don't show autotranslate button for organisation
* activate site: the super-admin can now set a site to 'public' which makes it appear in the app
* manager ('Verwalter') can now delete media files

Other
* prefix plugins
* remove landing page plugins
* set up unit and integration testing
* remove revisor role
* update wordpress and plugins
* automatic plugin activation

Manual tasks after merging:
* network activate webview themes
  * set active for all sites
  * set network webview theme active for landing page

### CODE REVIEW

**Comment by sven15** [comment]
the 403 fix is not working

**Comment by sven15** [comment]
New 403 fix commited and merged ... continuing testing

**Comment by mschrimpf** [comment]
@sven15 status? if it doesn't work, please revert the changes and we'll merge the rest.

**Comment by sven15** [comment]
@Meash you're refering to 403 error? Already applied a working hotfix to develop ;-)

**Comment by sven15** [comment]
Ah, the newest changes were not pulled on wordpress_test. Did that. just some minor changes, so no big retesting needed.

**Comment by mschrimpf** [comment]
Okay great. Then let's merge tomorrow (Thursday, May 5) after @sascha11110 committed the final changes for the webview.

**Comment by sascha11110** [comment]
Sorry for not getting it done any sooner. I added the minimal change via #367 

We could merge the webview but before we activate it, we need to add a separate picture of any instance (e.g. picture marketplace Augsburg). I will do that and the activation too.

**Pull request merged**
