### PR TITLE
Customized editor, German revisionary translations

### PR DESCRIPTION
**Pull request by sven15**
I've been using the test installation from time to time and did not come across any issues.
New features:
* customized editor plugin
* WP RTL (already present in master)
* removed automatic activation of push messages, wpml translation management
* german translations for revisionary

Important: We should first merge master back into develop to unify commit history.

### CODE REVIEW

**Comment by sven15** [comment]
on hold ... weird things happening in ig-content-loader-merge branch

**Comment by mschrimpf** [comment]
Too many changes that affect file mode etc. We'll have to revert+force-push `deploy`, then re-open this pull request.

**Comment by sven15** [comment]
Which file modes are desired? In this branch they are their standard wordpress mode.

**Comment by mschrimpf** [comment]
Leave it like the standard, they'll be changed back on every update.

**Pull request closed without merging**
