### PR TITLE
Update of Wordpress to 4.4.2 including current version of all Plugins

### PR DESCRIPTION
**Pull request by sven15**
There are some changes in the WP REST API plugin, for example some public functions have been removed or renamed. The compatibility with our App / protocol should be determined before merging to master branch.

### CODE REVIEW

**Comment by Meash** [comment]
The compatibility should also be checked before filing the pull request :p

**Comment by sven15** [comment]
do we have tests for compatability?

**Comment by Meash** [comment]
Nothing but your mouse as of now.

**Comment by Meash** [comment]
There's one other issue: Updating destroys some of our hacky changes, namely
1. in the WordPress core, we remove the "add existing user" div: see #90 and corresponding commits
2. we overrode all WPML flags with our own (`wp-content/plugins/sitepress-multilingual-cms/res/flags`)

For now, these two changes will have to be reverted. @sven15 can you do that please?

**Comment by sven15** [comment]
yep, I'll implement that into this branch

**Comment by Meash** [comment]
I'd rather automate it, someone will forget it at some point (probably me).
Or just get rid of the hackiness...

**Comment by sven15** [comment]
flags are unchanged

**Comment by sven15** [comment]
hide add existing user div is hidden again

**Pull request merged**
