### PR TITLE
Add event time zone

### LINKED ISSUE #927: Fix timezone for events API
**Describe the bug**
The events API does not deliver the timezone of the event. For example if you create an event in the cms which takes place in New York at 15:30 pm the API will just return 15:30 as start_time.

In the client we do not know how we should parse that string as we do not know which timezone.

As the modified_gmt is in GMT+0 the times of the events should use this aswell probably. Or use ISO 8601 with timezones: 2008-09-15T15:53:00*+05:00*

**To Reproduce**
* Create event in different timezone
* check times in api

### PR DESCRIPTION
**Pull request by svenseeberg**
* Add timezone of event in tz name format
* Fixes #927

### Your checklist for this pull request
- [x] Check if patches need to be applied.
  - [ ] Patch 0001 - WPML
  - [ ] Patch 0002 - Broken Link Checker
  - [ ] Patch 0003 - CMS Tree View
  - [ ] Patch 0004 - Sitepress
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your master!
- [x] Make sure you are making a pull request against the **develop branch** (left side). Also you should start *your branch* off *develop*.
- [x] Check the commit's or even all commits' message styles matches your requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

### CODE REVIEW

**Comment by maxammann** [comment]
Are we sure event_end_time is always Europe/Berlin? Or can it still be different if local time changes?

**Comment by svenseeberg** [comment]
It can differ for each event. But within one event, it is consistent.

**Comment by maxammann** [comment]
start_date end_date start_time end_time is always local time? So in our case Europe/Berlin?

**Comment by svenseeberg** [comment]
> start_date end_date start_time end_time is always local time? So in our case Europe/Berlin?

No, not always. The user can select the time zone during event creation. But as long as we are in Germany, it will probably always be `Europe/Berlin`, which is the default value in https://cms.integreat-app.de.

**Comment by maxammann** [comment]
I think the `start_date end_date start_time end_time` are not affected by the timezone at all. At least that is what my tests found out. Changing the timezone in the event creation does not affect the time delivered by the api.

**Comment by svenseeberg** [comment]
The time in the event is always a user selected time, which is always in the time zone selected in the same form.

**Pull request merged**
